services:
  redis:
    image: redis:7-alpine
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes


  db:
    image: postgres:15-alpine
    container_name: url_shortener_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    container_name: url_shortener_web
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # Celery Worker - Processes async tasks (like click tracking)
  celery_worker:
    build: .
    container_name: url_shortener_celery_worker
    command: celery -A url worker --loglevel=info
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # Celery Beat - Runs periodic tasks (like nightly cleanup)
  celery_beat:
    build: .
    container_name: url_shortener_celery_beat
    command: celery -A url beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  redis_data:
  postgres_data:

